CREATE TABLE `produktu` (
   `id` int(5) not null auto_increment,
   `izena` varchar(30) not null,
   `deskripzioa` text not null,
   `prezioa` float(7,2) not null,
   `stock` int(5) not null,
   `kategoria` varchar(15),
   PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=24;

INSERT INTO `produktu` (`id`, `izena`, `deskripzioa`, `prezioa`, `stock`, `kategoria`) VALUES 
('16', 'Peonia', 'Las peoniáceas (Paeoniaceae) constituyen una familia monogenérica de plantas dicotoledóneas rizomatosas originarias de diversas regiones de Europa, Extremo Oriente (especialmente de China) y de América del Norte, usualmente referidas como peonías.', '12.50', '200', 'Erramuak'),
('17', 'Lilium', 'Las especies de Lilium, comúnmente llamadas azucenas o lirios, constituyen un género con alrededor de 110 integrantes que se incluye dentro de la familia de las liliáceas.', '4.50', '123', 'Zentroak'),
('18', 'Laranjondoa', 'Laranjondoa (Citrus × sinensis) laranjak ekoizten dituen fruta-arbola da. Laranjondoa antzinatik landatzen den espezie hibridoa da, seguru asko arabisagar arbolaren (Citrus maxima) eta mandarinondoaren (Citrus reticulata) arteko nahastea. Zuhaitz loredun txikia da, 10 metro baino gutxiago hazten dena. Arrautza-formako hosto betiberde iraunkorrak ditu, 4 eta 10 cm artekoak, modu txandakatuan kokatuak eta ertz krenulatudunak. Bere fruitua den laranja hesperidio bat da, hau da, baia mota bat.', '6.30', '400', 'Zuhaitzak'),
('19', 'Pistatxondoa', 'Jatorriz, Iran eta Irakeko lurralde menditsuetakoa da, baina, gaur egun, Grezia, Siria, Iran, Kirgistan, Turkmenistan, Turkia, Pakistan, Afganistan, Egipto eta AEBetako Kalifornian ere landatzen da.\r\n\r\nPistatxondoak 10 m inguruko garaiera izaten du. Hosto pinatuak ditu, 10-20 cm-koak, zeinak askatu egiten baitira adarretatik ondu ondoren. Basamortuko landarea denez, ongi jasaten ditu lurzoru gaziak, eta gauza da muturreko tenperaturetan bizitzeko —neguan, 10 °C zero azpitik, eta, udan, 40 °C—. Eguzkira begira egon behar du, eta lurzoru drainatuan. Izan ere, ez da ongi garatzen hezetasun handiko lekuetan, eta sustraiak usteldu egin daitezke, ur gehiegi izanez gero. Uda luzeak komeni zaizkio, fruituak behar bezala ondu daitezen.', '30.00', '40', 'Zuhaitzak'),
('20', 'Geranioa', 'El género Geranium, comúnmente llamado geranio, agrupa 422 especies de plantas anuales, bienales y perennes frecuentemente utilizadas en jardinería por sus atractivas flores y su aroma característico. Su hábitat comprende todas las regiones templadas del mundo incluidas las zonas montañosas de los trópicos, aunque se encuentran mayoritariamente en la región oriental del Mediterráneo. Comprende 1216 especies descritas y de estas, solo 411 aceptadas.', '2.50', '500', 'Matujak'),
('21', 'Sagarrondoa', 'Orain dela 15.000 urte inguru sortu zela uste da, Kaukaso aldean. Europara erromatarrek ekarri zuten. Jatorri amerikarreko barietateak badaude ere, kontinente hartan kolonizatzaileen bitartez nagusiki zabaldu zen sagarrondoa. Gaur egun 1.000 barietate baino gehiago daude, espezie artean egin diren nahasteen ondorioz.\r\n\r\nErabileraren arabera, lau sagarrondo-mota bereizten dira: jateko sagarrak ematen dituztenak, sagardotarakoak, makatz edo basatiak (mentu-oin gisa erabiliak) eta apaingarriak. Sagarrondo kultibatuak (jateko eta sagardotarako sagarrak ematen dituztenak eta apaingarriak), oro har, txertatu egin ohi dira, eta sagarrondo-barietate desberdinak nahiz mentu-oinak hibridazioz lortzen dira.', '50.75', '45', 'Zuhaitzak'),
('22', 'Korona bariatuak', 'Koronak egiten ditugu edozein motako gertakizunentzako.', '120.50', '50', 'Funeralak'),
('23', 'Masusta', 'Masusta basa fruitu baten izena da, bi genero desberdinetako landareek ematen dutena: Morus (masustondoak) et Rubus (lahar edo sasiak). Bi generotako fruituek itxura eta zapore oso antzekoa dituzte. Ohikoena sasi edo laharretan hazten den masusta da. Fruitua heldu baino lehen, lore zuri edo arrosakarak dituzte, 2-3 cm zabalekoak. Masustak, heldu baino lehen, gorriak dira eta heltzean beltz urdinkarak.', '4.90', '500', 'Matujak');
